# Series

In [1]:
import pandas as pd
x=[1,2,3,4,5]
var = pd.Series(x,index=['a','b','c','d','e'],dtype="float")
print(var)

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64

# DataFrame

In [2]:
import pandas as pd
a=[1,2,3,4,5]
var = pd.DataFrame(a)
print(type(var))

<class 'pandas.DataFrame'>

# Arithmetic Operations

In [3]:
import pandas as pd

var = pd.DataFrame({"A":[1,2,3,4], "B":[5,6,7,8]})
var

   A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [4]:
var["C"] = var["A"]+var["B"]
var

   A  B   C
0  1  5   6
1  2  6   8
2  3  7  10
3  4  8  12

In [5]:
var["C"] = var["A"]-var["B"]
var

   A  B  C
0  1  5 -4
1  2  6 -4
2  3  7 -4
3  4  8 -4

In [6]:
var["C"] = var["A"]*var["B"]
var

   A  B   C
0  1  5   5
1  2  6  12
2  3  7  21
3  4  8  32

In [7]:
var["C"] = var["A"]/var["B"]
var

   A  B         C
0  1  5  0.200000
1  2  6  0.333333
2  3  7  0.428571
3  4  8  0.500000

In [8]:
var1 = pd.DataFrame({"A":[10,20,30,40], "B":[15,16,17,18]})
var1

    A   B
0  10  15
1  20  16
2  30  17
3  40  18

In [9]:
var1["Python"] = var1["A"] <= 20
var1["Python_1"] = var1["B"] >= 16
var1

    A   B  Python  Python_1
0  10  15    True     False
1  20  16    True      True
2  30  17   False      True
3  40  18   False      True