# Insert

In [1]:
import pandas as pd
var = pd.DataFrame({"A":[1,2,3,4,5], "B":[6,9,5,8,7]})
var

   A  B
0  1  6
1  2  9
2  3  5
3  4  8
4  5  7

In [2]:
var.insert(1,"Python",var["A"])
var

   A  Python  B
0  1       1  6
1  2       2  9
2  3       3  5
3  4       4  8
4  5       5  7

In [3]:
var.insert(1,"Python_1",[11,12,13,14,15])
var

   A  Python_1  Python  B
0  1        11       1  6
1  2        12       2  9
2  3        13       3  5
3  4        14       4  8
4  5        15       5  7

In [4]:
var["Python_2"] = var["A"][:3]
var

   A  Python_1  Python  B  Python_2
0  1        11       1  6       1.0
1  2        12       2  9       2.0
2  3        13       3  5       3.0
3  4        14       4  8       NaN
4  5        15       5  7       NaN

# Delete