# Replace

In [1]:
import pandas as pd
var = pd.read_csv(r"C:\Users\sachi\OneDrive\Product__Table.csv")
var

    ID   Product Name     Category  Price ($)  Stock Qty     Supplier
0    1      Alpha Pen   Stationery        1.5        120   OfficeMart
1    2  Beta Notebook   Stationery        3.2         85   PaperWorld
2    3    Gamma Chair    Furniture       45.0         40      FurniCo
3    4     Delta Desk    Furniture      120.0         25      FurniCo
4    5   Epsilon Lamp     Lighting       18.5         60   BrightLite
5    6     Zeta Mouse  Electronics       12.0        150     TechZone
6    7   Eta Keyboard  Electronics       25.0         90     TechZone
7    8  Theta Monitor  Electronics      150.0         35   VisionTech
8    9   Iota Printer  Electronics      200.0         20     PrintMax
9   10    Kappa Phone  Electronics      350.0         50    MobileHub
10  11   Lambda Cable  Electronics        5.0        300    WireWorks
11  12         Mu Mug      Kitchen        4.5        200  HomeEssence
12  13       Nu Plate      Kitchen        6.0        180  HomeEssence
13  14        Xi Bowl      Kitchen        7.5        160  HomeEssence
14  15    Omicron Pan      Kitchen       20.0         70     CookWell
15  16       Pi Knife      Kitchen       15.0         90    SharpEdge
16  17       Rho Sofa    Furniture      500.0         10      FurniCo
17  18      Sigma Bed    Furniture      750.0          8      FurniCo
18  19      Tau Shelf    Furniture       80.0         30      FurniCo
19  20    Upsilon Fan   Appliances       60.0         55      CoolAir
20  21         Phi AC   Appliances      400.0         15      CoolAir
21  22     Chi Heater   Appliances       70.0         25     WarmTech
22  23    Psi Blender   Appliances       55.0         40     CookWell
23  24  Omega Toaster   Appliances       35.0         50     CookWell
24  25   Zenith Watch      Fashion      120.0         75    StyleTime
25  26     Nova Shirt      Fashion       25.0        100    StyleTime

In [2]:
var.replace(to_replace="FurniCo",value="Python")

    ID   Product Name     Category  Price ($)  Stock Qty     Supplier
0    1      Alpha Pen   Stationery        1.5        120   OfficeMart
1    2  Beta Notebook   Stationery        3.2         85   PaperWorld
2    3    Gamma Chair    Furniture       45.0         40       Python
3    4     Delta Desk    Furniture      120.0         25       Python
4    5   Epsilon Lamp     Lighting       18.5         60   BrightLite
5    6     Zeta Mouse  Electronics       12.0        150     TechZone
6    7   Eta Keyboard  Electronics       25.0         90     TechZone
7    8  Theta Monitor  Electronics      150.0         35   VisionTech
8    9   Iota Printer  Electronics      200.0         20     PrintMax
9   10    Kappa Phone  Electronics      350.0         50    MobileHub
10  11   Lambda Cable  Electronics        5.0        300    WireWorks
11  12         Mu Mug      Kitchen        4.5        200  HomeEssence
12  13       Nu Plate      Kitchen        6.0        180  HomeEssence
13  14        Xi Bowl      Kitchen        7.5        160  HomeEssence
14  15    Omicron Pan      Kitchen       20.0         70     CookWell
15  16       Pi Knife      Kitchen       15.0         90    SharpEdge
16  17       Rho Sofa    Furniture      500.0         10       Python
17  18      Sigma Bed    Furniture      750.0          8       Python
18  19      Tau Shelf    Furniture       80.0         30       Python
19  20    Upsilon Fan   Appliances       60.0         55      CoolAir
20  21         Phi AC   Appliances      400.0         15      CoolAir
21  22     Chi Heater   Appliances       70.0         25     WarmTech
22  23    Psi Blender   Appliances       55.0         40     CookWell
23  24  Omega Toaster   Appliances       35.0         50     CookWell
24  25   Zenith Watch      Fashion      120.0         75    StyleTime
25  26     Nova Shirt      Fashion       25.0        100    StyleTime

In [3]:
var.replace([1,2,3,4,5,6,7,8,9,10,11],50)

    ID   Product Name     Category  Price ($)  Stock Qty     Supplier
0   50      Alpha Pen   Stationery        1.5        120   OfficeMart
1   50  Beta Notebook   Stationery        3.2         85   PaperWorld
2   50    Gamma Chair    Furniture       45.0         40      FurniCo
3   50     Delta Desk    Furniture      120.0         25      FurniCo
4   50   Epsilon Lamp     Lighting       18.5         60   BrightLite
5   50     Zeta Mouse  Electronics       12.0        150     TechZone
6   50   Eta Keyboard  Electronics       25.0         90     TechZone
7   50  Theta Monitor  Electronics      150.0         35   VisionTech
8   50   Iota Printer  Electronics      200.0         20     PrintMax
9   50    Kappa Phone  Electronics      350.0         50    MobileHub
10  50   Lambda Cable  Electronics       50.0        300    WireWorks
11  12         Mu Mug      Kitchen        4.5        200  HomeEssence
12  13       Nu Plate      Kitchen       50.0        180  HomeEssence
13  14        Xi Bowl      Kitchen        7.5        160  HomeEssence
14  15    Omicron Pan      Kitchen       20.0         70     CookWell
15  16       Pi Knife      Kitchen       15.0         90    SharpEdge
16  17       Rho Sofa    Furniture      500.0         50      FurniCo
17  18      Sigma Bed    Furniture      750.0         50      FurniCo
18  19      Tau Shelf    Furniture       80.0         30      FurniCo
19  20    Upsilon Fan   Appliances       60.0         55      CoolAir
20  21         Phi AC   Appliances      400.0         15      CoolAir
21  22     Chi Heater   Appliances       70.0         25     WarmTech
22  23    Psi Blender   Appliances       55.0         40     CookWell
23  24  Omega Toaster   Appliances       35.0         50     CookWell
24  25   Zenith Watch      Fashion      120.0         75    StyleTime
25  26     Nova Shirt      Fashion       25.0        100    StyleTime

In [4]:
var.replace("[A-Eg-p]","Python",regex=True)

,ID,Product Name,Category,Price ($),Stock Qty,Supplier
0,1,PythonPythonPythonPythona PePython,StatPythonPythonPythonery,1.5,120,OffPythonceMart
1,2,Pythoneta NPythontebPythonPythonPython,StatPythonPythonPythonery,3.2,85,PaPythonerWPythonrPythond
2,3,GaPythonPythona PythonPythonaPythonr,FurPythonPythonture,45.0,40,FurPythonPythonPythonPython
3,4,PythonePythonta PythonesPython,FurPythonPythonture,120.0,25,FurPythonPythonPythonPython
4,5,PythonPythonsPythonPythonPythonPython LaPython...,LPythonPythonPythontPythonPythonPython,18.5,60,PythonrPythonPythonPythontLPythonte
5,6,Zeta MPythonuse,PythonPythonectrPythonPythonPythoncs,12.0,150,TecPythonZPythonPythone
6,7,Pythonta KeybPythonard,PythonPythonectrPythonPythonPythoncs,25.0,90,TecPythonZPythonPythone
7,8,TPythoneta MPythonPythonPythontPythonr,PythonPythonectrPythonPythonPythoncs,150.0,35,VPythonsPythonPythonPythonTecPython
8,9,IPythonta PrPythonPythonter,PythonPythonectrPythonPythonPythoncs,200.0,20,PrPythonPythontMax
9,10,KaPythonPythona PPythonPythonPythone,PythonPythonectrPythonPythonPythoncs,350.0,50,MPythonbPythonPythoneHub
10,11,LaPythonbda PythonabPythone,PythonPythonectrPythonPythonPythoncs,5.0,300,WPythonreWPythonrPythons
11,12,Mu MuPython,KPythontcPythonePython,4.5,200,HPythonPythonePythonssePythonce
12,13,Nu PPythonate,KPythontcPythonePython,6.0,180,HPythonPythonePythonssePythonce
13,14,XPython PythonPythonwPython,KPythontcPythonePython,7.5,160,HPythonPythonePythonssePythonce
14,15,OPythonPythoncrPythonPython PaPython,KPythontcPythonePython,20.0,70,PythonPythonPythonPythonWePythonPython
15,16,PPython KPythonPythonfe,KPythontcPythonePython,15.0,90,SPythonarPythonPythondPythone
16,17,RPythonPython SPythonfa,FurPythonPythonture,500.0,10,FurPythonPythonPythonPython
17,18,SPythonPythonPythona Pythoned,FurPythonPythonture,750.0,8,FurPythonPythonPythonPython
18,19,Tau SPythonePythonf,FurPythonPythonture,80.0,30,FurPythonPythonPythonPython
19,20,UPythonsPythonPythonPythonPython FaPython,PythonPythonPythonPythonPythonaPythonces,60.0,55,PythonPythonPythonPythonPythonPythonr
20,21,PPythonPython PythonPython,PythonPythonPythonPythonPythonaPythonces,400.0,15,PythonPythonPythonPythonPythonPythonr
21,22,PythonPythonPython Heater,PythonPythonPythonPythonPythonaPythonces,70.0,25,WarPythonTecPython
22,23,PsPython PythonPythonePythonder,PythonPythonPythonPythonPythonaPythonces,55.0,40,PythonPythonPythonPythonWePythonPython
23,24,OPythonePythona TPythonaster,PythonPythonPythonPythonPythonaPythonces,35.0,50,PythonPythonPythonPythonWePythonPython
24,25,ZePythonPythontPython WatcPython,FasPythonPythonPythonPython,120.0,75,StyPythoneTPythonPythone
25,26,NPythonva SPythonPythonrt,FasPythonPythonPythonPython,25.0,100,StyPythoneTPythonPythone

In [5]:
var.replace({"Product Name":"[A-Z]"},95,regex=True)

    ID Product Name     Category  Price ($)  Stock Qty     Supplier
0    1           95   Stationery        1.5        120   OfficeMart
1    2           95   Stationery        3.2         85   PaperWorld
2    3           95    Furniture       45.0         40      FurniCo
3    4           95    Furniture      120.0         25      FurniCo
4    5           95     Lighting       18.5         60   BrightLite
5    6           95  Electronics       12.0        150     TechZone
6    7           95  Electronics       25.0         90     TechZone
7    8           95  Electronics      150.0         35   VisionTech
8    9           95  Electronics      200.0         20     PrintMax
9   10           95  Electronics      350.0         50    MobileHub
10  11           95  Electronics        5.0        300    WireWorks
11  12           95      Kitchen        4.5        200  HomeEssence
12  13           95      Kitchen        6.0        180  HomeEssence
13  14           95      Kitchen        7.5        160  HomeEssence
14  15           95      Kitchen       20.0         70     CookWell
15  16           95      Kitchen       15.0         90    SharpEdge
16  17           95    Furniture      500.0         10      FurniCo
17  18           95    Furniture      750.0          8      FurniCo
18  19           95    Furniture       80.0         30      FurniCo
19  20           95   Appliances       60.0         55      CoolAir
20  21           95   Appliances      400.0         15      CoolAir
21  22           95   Appliances       70.0         25     WarmTech
22  23           95   Appliances       55.0         40     CookWell
23  24           95   Appliances       35.0         50     CookWell
24  25           95      Fashion      120.0         75    StyleTime
25  26           95      Fashion       25.0        100    StyleTime