# Fillna

In [1]:
import pandas as pd
var = pd.read_csv(r"C:\Users\sachi\OneDrive\product__table 1.csv")
var

    ID   Product Name     Category  Price ($)  Stock Qty     Supplier
0    1      Alpha Pen   Stationery        1.5      120.0   OfficeMart
1    2  Beta Notebook   Stationery        3.2       85.0   PaperWorld
2    3    Gamma Chair    Furniture       45.0       40.0      FurniCo
3    4     Delta Desk    Furniture      120.0       25.0          NaN
4    5   Epsilon Lamp     Lighting       18.5       60.0   BrightLite
5    6     Zeta Mouse  Electronics       12.0      150.0          NaN
6    7   Eta Keyboard  Electronics       25.0       90.0     TechZone
7    8  Theta Monitor  Electronics      150.0       35.0   VisionTech
8    9   Iota Printer          NaN      200.0       20.0     PrintMax
9   10    Kappa Phone  Electronics      350.0       50.0    MobileHub
10  11   Lambda Cable  Electronics        5.0        NaN    WireWorks
11  12         Mu Mug          NaN        4.5      200.0          NaN
12  13       Nu Plate          NaN        NaN      180.0  HomeEssence
13  14        Xi Bowl      Kitchen        7.5      160.0  HomeEssence
14  15    Omicron Pan      Kitchen       20.0       70.0          NaN
15  16       Pi Knife      Kitchen       15.0       90.0    SharpEdge
16  17       Rho Sofa    Furniture      500.0       10.0      FurniCo
17  18      Sigma Bed          NaN      750.0        8.0      FurniCo
18  19      Tau Shelf    Furniture       80.0       30.0          NaN
19  20    Upsilon Fan   Appliances       60.0        NaN      CoolAir
20  21         Phi AC   Appliances        NaN       15.0      CoolAir
21  22     Chi Heater   Appliances       70.0       25.0     WarmTech
22  23    Psi Blender          NaN       55.0       40.0          NaN
23  24  Omega Toaster   Appliances       35.0       50.0     CookWell
24  25   Zenith Watch      Fashion        NaN       75.0    StyleTime
25  26     Nova Shirt      Fashion       25.0      100.0    StyleTime

In [2]:
var.fillna("Python")

    ID   Product Name     Category Price ($) Stock Qty     Supplier
0    1      Alpha Pen   Stationery       1.5     120.0   OfficeMart
1    2  Beta Notebook   Stationery       3.2      85.0   PaperWorld
2    3    Gamma Chair    Furniture      45.0      40.0      FurniCo
3    4     Delta Desk    Furniture     120.0      25.0       Python
4    5   Epsilon Lamp     Lighting      18.5      60.0   BrightLite
5    6     Zeta Mouse  Electronics      12.0     150.0       Python
6    7   Eta Keyboard  Electronics      25.0      90.0     TechZone
7    8  Theta Monitor  Electronics     150.0      35.0   VisionTech
8    9   Iota Printer       Python     200.0      20.0     PrintMax
9   10    Kappa Phone  Electronics     350.0      50.0    MobileHub
10  11   Lambda Cable  Electronics       5.0    Python    WireWorks
11  12         Mu Mug       Python       4.5     200.0       Python
12  13       Nu Plate       Python    Python     180.0  HomeEssence
13  14        Xi Bowl      Kitchen       7.5     160.0  HomeEssence
14  15    Omicron Pan      Kitchen      20.0      70.0       Python
15  16       Pi Knife      Kitchen      15.0      90.0    SharpEdge
16  17       Rho Sofa    Furniture     500.0      10.0      FurniCo
17  18      Sigma Bed       Python     750.0       8.0      FurniCo
18  19      Tau Shelf    Furniture      80.0      30.0       Python
19  20    Upsilon Fan   Appliances      60.0    Python      CoolAir
20  21         Phi AC   Appliances    Python      15.0      CoolAir
21  22     Chi Heater   Appliances      70.0      25.0     WarmTech
22  23    Psi Blender       Python      55.0      40.0       Python
23  24  Omega Toaster   Appliances      35.0      50.0     CookWell
24  25   Zenith Watch      Fashion    Python      75.0    StyleTime
25  26     Nova Shirt      Fashion      25.0     100.0    StyleTime

In [3]:
var.fillna({"Category":"Java","Supplier":"Python"})

    ID   Product Name     Category  Price ($)  Stock Qty     Supplier
0    1      Alpha Pen   Stationery        1.5      120.0   OfficeMart
1    2  Beta Notebook   Stationery        3.2       85.0   PaperWorld
2    3    Gamma Chair    Furniture       45.0       40.0      FurniCo
3    4     Delta Desk    Furniture      120.0       25.0       Python
4    5   Epsilon Lamp     Lighting       18.5       60.0   BrightLite
5    6     Zeta Mouse  Electronics       12.0      150.0       Python
6    7   Eta Keyboard  Electronics       25.0       90.0     TechZone
7    8  Theta Monitor  Electronics      150.0       35.0   VisionTech
8    9   Iota Printer         Java      200.0       20.0     PrintMax
9   10    Kappa Phone  Electronics      350.0       50.0    MobileHub
10  11   Lambda Cable  Electronics        5.0        NaN    WireWorks
11  12         Mu Mug         Java        4.5      200.0       Python
12  13       Nu Plate         Java        NaN      180.0  HomeEssence
13  14        Xi Bowl      Kitchen        7.5      160.0  HomeEssence
14  15    Omicron Pan      Kitchen       20.0       70.0       Python
15  16       Pi Knife      Kitchen       15.0       90.0    SharpEdge
16  17       Rho Sofa    Furniture      500.0       10.0      FurniCo
17  18      Sigma Bed         Java      750.0        8.0      FurniCo
18  19      Tau Shelf    Furniture       80.0       30.0       Python
19  20    Upsilon Fan   Appliances       60.0        NaN      CoolAir
20  21         Phi AC   Appliances        NaN       15.0      CoolAir
21  22     Chi Heater   Appliances       70.0       25.0     WarmTech
22  23    Psi Blender         Java       55.0       40.0       Python
23  24  Omega Toaster   Appliances       35.0       50.0     CookWell
24  25   Zenith Watch      Fashion        NaN       75.0    StyleTime
25  26     Nova Shirt      Fashion       25.0      100.0    StyleTime

In [4]:
var.ffill(axis =0)

    ID   Product Name     Category  Price ($)  Stock Qty     Supplier
0    1      Alpha Pen   Stationery        1.5      120.0   OfficeMart
1    2  Beta Notebook   Stationery        3.2       85.0   PaperWorld
2    3    Gamma Chair    Furniture       45.0       40.0      FurniCo
3    4     Delta Desk    Furniture      120.0       25.0      FurniCo
4    5   Epsilon Lamp     Lighting       18.5       60.0   BrightLite
5    6     Zeta Mouse  Electronics       12.0      150.0   BrightLite
6    7   Eta Keyboard  Electronics       25.0       90.0     TechZone
7    8  Theta Monitor  Electronics      150.0       35.0   VisionTech
8    9   Iota Printer  Electronics      200.0       20.0     PrintMax
9   10    Kappa Phone  Electronics      350.0       50.0    MobileHub
10  11   Lambda Cable  Electronics        5.0       50.0    WireWorks
11  12         Mu Mug  Electronics        4.5      200.0    WireWorks
12  13       Nu Plate  Electronics        4.5      180.0  HomeEssence
13  14        Xi Bowl      Kitchen        7.5      160.0  HomeEssence
14  15    Omicron Pan      Kitchen       20.0       70.0  HomeEssence
15  16       Pi Knife      Kitchen       15.0       90.0    SharpEdge
16  17       Rho Sofa    Furniture      500.0       10.0      FurniCo
17  18      Sigma Bed    Furniture      750.0        8.0      FurniCo
18  19      Tau Shelf    Furniture       80.0       30.0      FurniCo
19  20    Upsilon Fan   Appliances       60.0       30.0      CoolAir
20  21         Phi AC   Appliances       60.0       15.0      CoolAir
21  22     Chi Heater   Appliances       70.0       25.0     WarmTech
22  23    Psi Blender   Appliances       55.0       40.0     WarmTech
23  24  Omega Toaster   Appliances       35.0       50.0     CookWell
24  25   Zenith Watch      Fashion       35.0       75.0    StyleTime
25  26     Nova Shirt      Fashion       25.0      100.0    StyleTime

In [5]:
var.bfill(axis =1)

    ID   Product Name     Category Price ($)  Stock Qty     Supplier
0    1      Alpha Pen   Stationery       1.5      120.0   OfficeMart
1    2  Beta Notebook   Stationery       3.2       85.0   PaperWorld
2    3    Gamma Chair    Furniture      45.0       40.0      FurniCo
3    4     Delta Desk    Furniture     120.0       25.0          NaN
4    5   Epsilon Lamp     Lighting      18.5       60.0   BrightLite
5    6     Zeta Mouse  Electronics      12.0      150.0          NaN
6    7   Eta Keyboard  Electronics      25.0       90.0     TechZone
7    8  Theta Monitor  Electronics     150.0       35.0   VisionTech
8    9   Iota Printer        200.0     200.0       20.0     PrintMax
9   10    Kappa Phone  Electronics     350.0       50.0    MobileHub
10  11   Lambda Cable  Electronics       5.0  WireWorks    WireWorks
11  12         Mu Mug          4.5       4.5      200.0          NaN
12  13       Nu Plate        180.0     180.0      180.0  HomeEssence
13  14        Xi Bowl      Kitchen       7.5      160.0  HomeEssence
14  15    Omicron Pan      Kitchen      20.0       70.0          NaN
15  16       Pi Knife      Kitchen      15.0       90.0    SharpEdge
16  17       Rho Sofa    Furniture     500.0       10.0      FurniCo
17  18      Sigma Bed        750.0     750.0        8.0      FurniCo
18  19      Tau Shelf    Furniture      80.0       30.0          NaN
19  20    Upsilon Fan   Appliances      60.0    CoolAir      CoolAir
20  21         Phi AC   Appliances      15.0       15.0      CoolAir
21  22     Chi Heater   Appliances      70.0       25.0     WarmTech
22  23    Psi Blender         55.0      55.0       40.0          NaN
23  24  Omega Toaster   Appliances      35.0       50.0     CookWell
24  25   Zenith Watch      Fashion      75.0       75.0    StyleTime
25  26     Nova Shirt      Fashion      25.0      100.0    StyleTime

In [6]:
var.fillna("Python",limit = 3)

    ID   Product Name     Category Price ($) Stock Qty     Supplier
0    1      Alpha Pen   Stationery       1.5     120.0   OfficeMart
1    2  Beta Notebook   Stationery       3.2      85.0   PaperWorld
2    3    Gamma Chair    Furniture      45.0      40.0      FurniCo
3    4     Delta Desk    Furniture     120.0      25.0       Python
4    5   Epsilon Lamp     Lighting      18.5      60.0   BrightLite
5    6     Zeta Mouse  Electronics      12.0     150.0       Python
6    7   Eta Keyboard  Electronics      25.0      90.0     TechZone
7    8  Theta Monitor  Electronics     150.0      35.0   VisionTech
8    9   Iota Printer       Python     200.0      20.0     PrintMax
9   10    Kappa Phone  Electronics     350.0      50.0    MobileHub
10  11   Lambda Cable  Electronics       5.0    Python    WireWorks
11  12         Mu Mug       Python       4.5     200.0       Python
12  13       Nu Plate       Python    Python     180.0  HomeEssence
13  14        Xi Bowl      Kitchen       7.5     160.0  HomeEssence
14  15    Omicron Pan      Kitchen      20.0      70.0          NaN
15  16       Pi Knife      Kitchen      15.0      90.0    SharpEdge
16  17       Rho Sofa    Furniture     500.0      10.0      FurniCo
17  18      Sigma Bed          NaN     750.0       8.0      FurniCo
18  19      Tau Shelf    Furniture      80.0      30.0          NaN
19  20    Upsilon Fan   Appliances      60.0    Python      CoolAir
20  21         Phi AC   Appliances    Python      15.0      CoolAir
21  22     Chi Heater   Appliances      70.0      25.0     WarmTech
22  23    Psi Blender          NaN      55.0      40.0          NaN
23  24  Omega Toaster   Appliances      35.0      50.0     CookWell
24  25   Zenith Watch      Fashion    Python      75.0    StyleTime
25  26     Nova Shirt      Fashion      25.0     100.0    StyleTime