# Merge

In [1]:
import pandas as pd
var1 = pd.DataFrame({"A":[1,2,3,4,5], "B":[11,12,13,14,15]})
var2 = pd.DataFrame({"A":[1,2,3,4,6], "C":[21,22,23,24,25]})
pd.merge(var1,var2,on="A")

   A   B   C
0  1  11  21
1  2  12  22
2  3  13  23
3  4  14  24

In [2]:
pd.merge(var1,var2,how="left")

   A   B     C
0  1  11  21.0
1  2  12  22.0
2  3  13  23.0
3  4  14  24.0
4  5  15   NaN

In [3]:
pd.merge(var1,var2,how="right")

   A     B   C
0  1  11.0  21
1  2  12.0  22
2  3  13.0  23
3  4  14.0  24
4  6   NaN  25

In [4]:
pd.merge(var1,var2,how="outer")

   A     B     C
0  1  11.0  21.0
1  2  12.0  22.0
2  3  13.0  23.0
3  4  14.0  24.0
4  5  15.0   NaN
5  6   NaN  25.0

In [5]:
pd.merge(var1,var2,left_index=True,right_index=True)

   A_x   B  A_y   C
0    1  11    1  21
1    2  12    2  22
2    3  13    3  23
3    4  14    4  24
4    5  15    6  25

# Concat

In [6]:
sr1 = pd.Series([1,2,3,4,5])
sr2 = pd.Series([12,24,35,48,50])
pd.concat([sr1,sr2])

0     1
1     2
2     3
3     4
4     5
0    12
1    24
2    35
3    48
4    50
dtype: int64

In [7]:
d1 = pd.DataFrame({"A":[1,2,3,4,5], "B":[11,12,13,14,15]})
d2 = pd.DataFrame({"A":[1,2,3,4,6], "B":[21,22,23,24,25]})
pd.concat([d1,d2])

   A   B
0  1  11
1  2  12
2  3  13
3  4  14
4  5  15
0  1  21
1  2  22
2  3  23
3  4  24
4  6  25

In [8]:
pd.concat([d1,d2],axis=1,join="outer")

   A   B  A   B
0  1  11  1  21
1  2  12  2  22
2  3  13  3  23
3  4  14  4  24
4  5  15  6  25

In [9]:
pd.concat([d1,d2],axis=0,join="inner")

   A   B
0  1  11
1  2  12
2  3  13
3  4  14
4  5  15
0  1  21
1  2  22
2  3  23
3  4  24
4  6  25

In [10]:
pd.concat([d1,d2],axis=1,keys=["d1","d2"])

  d1     d2
   A   B  A   B
0  1  11  1  21
1  2  12  2  22
2  3  13  3  23
3  4  14  4  24
4  5  15  6  25

In [11]:
pd.concat([d1,d2],axis=0,keys=["d1","d2"])

      A   B
d1 0  1  11
   1  2  12
   2  3  13
   3  4  14
   4  5  15
d2 0  1  21
   1  2  22
   2  3  23
   3  4  24
   4  6  25